[package]
name = "ReactDevtoolsShared"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Shared = { path = "../shared" }
React = { path = "../react" }
ReactReconciler = { path = "../react-reconciler" }
ReactRoblox = { path = "../react-roblox" }
ReactIs = { path = "../react-is" }
ReactDebugTools = { path = "../react-debug-tools" }

[dev_dependencies]
JestRoblox = { workspace = true }
RobloxJest = { path = "../roblox-jest" }
Scheduler = { path = "../scheduler" }
Promise = { workspace = true }
ReactTestRenderer = { path = "../react-test-renderer" }
DeveloperTools = "github.com/Roblox/developer-tools@0.2"
