[package]
name = "ReactDebugTools"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"

[dependencies]
LuauPolyfill = { workspace = true }
Shared = { path = "../shared" }
ReactReconciler = { path = "../react-reconciler" }
ReactIs = { path = "../react-is" }

[dev_dependencies]
JestRoblox = { workspace = true }
RobloxJest = { path = "../roblox-jest" }
Scheduler = { path = "../scheduler" }
