[package]
name = "ReactDebugTools"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"

[dependencies]
LuauPolyfill = { workspace = true }
Shared = { path = "../shared" }
ReactReconciler = { path = "../react-reconciler" }
