[tools]
rotrieve = { source = "roblox/rotriever", version = "=0.5.4" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
selene = { source = "Kampfkarren/selene", version = "0.16.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.12.5" }
testez = { source = "roblox/testez", version = "0.3.2" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
