[tools]
rotrieve = { source = "roblox/rotriever", version = "0.4.2" }
rojo = { source = "rojo-rbx/rojo", version = "6.0.1" }
selene = { source = "Kampfkarren/selene", version = "0.11.0" }
testez = { source = "roblox/testez", version = "0.3.2" }
