[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.0-alpha.3" }
rojo = { source = "rojo-rbx/rojo", version = "6.0.1" }
selene = { source = "Kampfkarren/selene", version = "0.12.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.9.3" }
testez = { source = "roblox/testez", version = "0.3.2" }
