site_name: Roact Documentation
site_url: https://roblox.github.io/roact/
repo_name: Roblox/roact
repo_url: https://github.com/Roblox/roact

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" #
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 
      primary: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Migrating From 1.x: migrating-from-roact-1x.md
  - Deviations: deviations.md
  - API Reference:
    - React: api-reference/react.md
    - ReactRoblox: api-reference/react-roblox.md
    - RoactCompat: api-reference/roact-compat.md
    - Additional Libraries: api-reference/additional-libraries.md
  - Benchmarks: bench.md

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
