site_name: Roact Documentation
site_url: https://roblox.github.io/roact/
repo_name: Roblox/roact
repo_url: https://github.com/Roblox/roact

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
    scheme: preference

nav:
  - Home: index.md
  - Adoption: migrating-from-roact.md
  - Deviations: deviations.md
  - API Reference: api-reference.md

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
