[package]
name = "ReactTelemetry"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
ReactGlobals = { path = "../react-globals" }
LuauPolyfill = { workspace = true }
SafeFlags = { workspace = true }

[dev_dependencies]
JestGlobals = { workspace = true }
