[package]
name = "RobloxJest"
version = { workspace = true }
authors = { workspace = true }
publish = false
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }

[dev_dependencies]
JestRoblox = { workspace = true }
