[package]
name = "RobloxJest"
version = { workspace = true }
authors = { workspace = true }
publish = false
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
JestDiff = "github.com/roblox/jest-roblox@2.1.4"

[dev_dependencies]
JestGlobals = { workspace = true }
