[package]
name = "Roact17"
version = "17.0.1-rc.19"
content_root = "src"

[dependencies]
RoactCompat = "github.com/roblox/roact-alignment@17.0.1-rc.19"
React = "github.com/roblox/roact-alignment@17.0.1-rc.19"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.19"
ReactIs = "github.com/roblox/roact-alignment@17.0.1-rc.19"
