[package]
name = "Roact17"
version = "17.0.1"
content_root = "src"

[dependencies]
RoactCompat = "github.com/roblox/roact-alignment@17.0.1"
React = "github.com/roblox/roact-alignment@17.0.1"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1"
ReactIs = "github.com/roblox/roact-alignment@17.0.1"
