[package]
name = "ReactDevtoolsExtensions"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
Shared = { path = "../shared" }
React = { path = "../react" }
ReactDevtoolsShared = { path = "../react-devtools-shared" }
ReactRoblox = { path = "../react-roblox" }

[dev_dependencies]
JestGlobals ={ workspace = true }
RobloxJest = { path = "../roblox-jest" }
DeveloperTools = "github.com/Roblox/developer-tools@0.2.2"
ReactTestRenderer = { path = "../react-test-renderer" }