[package]
name = "ReactReconciler"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
Scheduler = { path = "../scheduler" }
Shared = { path = "../shared" }
React = { path = "../react" }

[dev_dependencies]
JestGlobals ={ workspace = true }
JestReact = { path = "../jest-react" }
ReactCache = { path = "../react-cache" }
ReactNoopRenderer = { path = "../react-noop-renderer" }
ReactTestRenderer = { path = "../react-test-renderer" }
ReactRoblox = { path = "../react-roblox" }
ReactDevtoolsShared = { path = "../react-devtools-shared" }
