[package]
name = "Scheduler"
version = { workspace = true }
authors = { workspace = true }
publish = false
content_root = "src"

[dependencies]
LuauPolyfill = { workspace = true }
Shared = { path = "../shared" }

[dev_dependencies]
JestRoblox = { workspace = true }
RobloxJest = { path = "../roblox-jest" }
