[package]
name = "Scheduler"
version = { workspace = true }
authors = { workspace = true }
publish = false
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Shared = { path = "../shared" }

[dev_dependencies]
JestGlobals ={ workspace = true }
