[package]
name = "Scheduler"
version = { workspace = true }
authors = { workspace = true }
publish = false
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
SafeFlags = { workspace = true }
ReactGlobals = { path = "../react-globals" }
Shared = { path = "../shared" }

[dev_dependencies]
JestGlobals = { workspace = true }
