[package]
name = "RoactCompat"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
React = { path = "../react" }
ReactRoblox = { path = "../react-roblox" }
Shared = { path = "../shared" }

[dev_dependencies]
Roact = "github.com/roblox/roact@1.4.0"
JestGlobals ={ workspace = true }
Scheduler = { path = "../scheduler" }
