[package]
name = "React"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Cryo = { workspace = true }
Shared = { path = "../shared" }

[dev_dependencies]
JestReact = { path = "../jest-react" }
JestRoblox = { workspace = true }
Promise = { workspace = true}
RobloxJest = { path = "../roblox-jest" }
ReactCache = { path = "../react-cache" }
ReactNoopRenderer = { path = "../react-noop-renderer" }
ReactRoblox = { path = "../react-roblox" }
ReactTestRenderer = { path = "../react-test-renderer" }
Scheduler = { path = "../scheduler" }
